In [27]:
import pandas as pd
import numpy as np

In [28]:
income = pd.read_csv('../../data/clean/income_clean_stage1.csv')

rental = pd.read_excel('../../data/clean/Rental_Clean_Stage1.xlsx')

population = pd.read_csv('../../data/clean/Population_Clean_Stage1.csv')

housing = pd.read_csv('../../data/clean/housing_price_clean_stage1.csv')

In [29]:
income.shape
rental.shape
population.shape
housing.shape

(1280, 4)

In [30]:
income.info()
rental.info()
population.info()
housing.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   City         20 non-null     str
 1   City_ID      20 non-null     str
 2   Income_Type  20 non-null     str
 3   Income       20 non-null     int64
dtypes: int64(1), str(3)
memory usage: 772.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             5 non-null      str
 1   Vacancy_2024     5 non-null      float64
 2   Vacancy_2025     5 non-null      float64
 3   Turnover_2024    5 non-null      float64
 4   Turnover_2025    5 non-null      float64
 5   Rent_2024        5 non-null      str
 6   Rent_2025        5 non-null      str
 7   RentGrowth_2024  5 non-null      float64
 8   RentGrowth_2025  4 non-null      float64
dtypes: float64(6), str(3)
memory usage: 492.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        25 non-null     int64
 1   City        25 non-null     str
 2   City_ID     25 non-null     str
 3   Population  25 non-null     int64
dtypes: int64(2), str(2)
memory usage: 932.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1280 non-null   str
 1   City                 1280 non-null   str
 2   City_ID              1280 non-null   str
 3   Housing_Price_Index  1280 non-null   float64
dtypes: float64(1), str(3)
memory usage: 40.1 KB

In [31]:
rental.head()

,City,Vacancy_2024,Vacancy_2025,Turnover_2024,Turnover_2025,Rent_2024,Rent_2025,RentGrowth_2024,RentGrowth_2025
0,Montréal CMA,2.1,2.9,11.1,9.4,"1,176","1,346",6.3,7.2
1,Ottawa-Gatineau CMA,2.6,3.0,14.5,15.4,"1,880","1,926",5.0,3.4
2,Toronto CMA,2.5,3.0,6.4,8.7,"1,974","2,046",2.7,3.4
3,Calgary CMA,4.8,5.0,23.6,24.9,"1,882","1,914",8.9,NaN
4,Vancouver CMA,1.6,3.7,9.1,11.6,"2,314","2,363",5.5,2.2

In [32]:
rental.isnull().sum()

City               0
Vacancy_2024       0
Vacancy_2025       0
Turnover_2024      0
Turnover_2025      0
Rent_2024          0
Rent_2025          0
RentGrowth_2024    0
RentGrowth_2025    1
dtype: int64

In [33]:
rental['Rent_2024'] = rental['Rent_2024'].str.replace(',', '').astype(float)
rental['Rent_2025'] = rental['Rent_2025'].str.replace(',', '').astype(float)

In [34]:
rental.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             5 non-null      str
 1   Vacancy_2024     5 non-null      float64
 2   Vacancy_2025     5 non-null      float64
 3   Turnover_2024    5 non-null      float64
 4   Turnover_2025    5 non-null      float64
 5   Rent_2024        5 non-null      float64
 6   Rent_2025        5 non-null      float64
 7   RentGrowth_2024  5 non-null      float64
 8   RentGrowth_2025  4 non-null      float64
dtypes: float64(8), str(1)
memory usage: 492.0 bytes

In [35]:
housing.head()

      Date          City       City_ID  Housing_Price_Index
0  2005-01  Montréal CMA  2011S0503462                 75.9
1  2005-02  Montréal CMA  2011S0503462                 76.2
2  2005-03  Montréal CMA  2011S0503462                 76.7
3  2005-04  Montréal CMA  2011S0503462                 76.9
4  2005-05  Montréal CMA  2011S0503462                 76.9

In [36]:
housing['Date'] = pd.to_datetime(housing['Date'])

In [37]:
housing['Year'] = housing['Date'].dt.year
#To create a common key (Year) that can be used to merge the housing dataset with the other annual datasets.

In [38]:
housing_yearly = housing.groupby(['City', 'City_ID', 'Year'])['Housing_Price_Index'].mean().reset_index()
#To convert monthly housing price index values into annual averages so that the dataset aligns with the annual frequency of the other datasets.

In [39]:
housing_yearly.head()

           City       City_ID  Year  Housing_Price_Index
0  Calgary CMA   2011S0503825  2005            54.683333
1  Calgary CMA   2011S0503825  2006            78.558333
2  Calgary CMA   2011S0503825  2007            91.241667
3  Calgary CMA   2011S0503825  2008            91.833333
4  Calgary CMA   2011S0503825  2009            85.708333

In [40]:
housing_yearly = housing_yearly[
    housing_yearly['Year'].between(2021, 2025)
]
#The Housing Price Index dataset was filtered to the 2021–2025 period to align with the project's focus on current housing affordability and ensure temporal consistency with the population and rental datasets.

In [41]:
housing_yearly['Year'].unique()

array([2021, 2022, 2023, 2024, 2025], dtype=int32)

In [42]:
housing_yearly.shape

(25, 4)

In [43]:
income.head()

,City,City_ID,Income_Type,Income
0,Calgary CMA,2021S0503825,Median household total income (2020) (2020 con...,100000
1,Calgary CMA,2021S0503825,Median household total income (2015) (2020 con...,108000
2,Calgary CMA,2021S0503825,Median household after-tax income (2020) (2020...,87000
3,Calgary CMA,2021S0503825,Median household after-tax income (2015) (2020...,92000
4,Montréal CMA,2021S0503462,Median household total income (2020) (2020 con...,76000

In [44]:
income_2020 = income[
    income['Income_Type'].str.contains('(2020)', regex=False)
]

In [45]:
income_2020.head()

,City,City_ID,Income_Type,Income
0,Calgary CMA,2021S0503825,Median household total income (2020) (2020 con...,100000
2,Calgary CMA,2021S0503825,Median household after-tax income (2020) (2020...,87000
4,Montréal CMA,2021S0503462,Median household total income (2020) (2020 con...,76000
6,Montréal CMA,2021S0503462,Median household after-tax income (2020) (2020...,65500
8,Ottawa-Gatineau CMA,2021S0503505,Median household total income (2020) (2020 con...,98000

In [46]:
income_2020.shape

(10, 4)

In [47]:
income_pivot = income_2020.pivot(
    index=['City', 'City_ID'],
    columns='Income_Type',
    values='Income'
).reset_index()
#A pivot operation transforms rows into columns.

In [48]:
income_pivot.head()

Income_Type,City,City_ID,Median household after-tax income (2020) (2020 constant dollars),Median household total income (2020) (2020 constant dollars)
0,Calgary CMA,2021S0503825,87000,100000
1,Montréal CMA,2021S0503462,65500,76000
2,Ottawa-Gatineau CMA,2021S0503505,84000,98000
3,Toronto CMA,2021S0503535,85000,97000
4,Vancouver CMA,2021S0503933,79500,90000

In [49]:
income_pivot.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   City                                                              5 non-null      str
 1   City_ID                                                           5 non-null      str
 2   Median household after-tax income (2020) (2020 constant dollars)  5 non-null      int64
 3   Median household total income (2020) (2020 constant dollars)      5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [50]:
income_pivot = income_pivot.rename(columns={
    'Median household after-tax income (2020) (2020 constant dollars)': 'AfterTax_Income_2020',
    'Median household total income (2020) (2020 constant dollars)': 'Total_Income_2020'
})

In [51]:
income_pivot.head()

Income_Type,City,City_ID,AfterTax_Income_2020,Total_Income_2020
0,Calgary CMA,2021S0503825,87000,100000
1,Montréal CMA,2021S0503462,65500,76000
2,Ottawa-Gatineau CMA,2021S0503505,84000,98000
3,Toronto CMA,2021S0503535,85000,97000
4,Vancouver CMA,2021S0503933,79500,90000

In [52]:
master = pd.merge(
    population,
    housing_yearly,
    on=['City', 'City_ID', 'Year'],
    how='left'
)

master.head()
master.info()

KeyError: 'Year'

In [53]:
population.columns

Index(['Year ', 'City', 'City_ID', 'Population'], dtype='str')

In [54]:
housing_yearly.columns

Index(['City', 'City_ID', 'Year', 'Housing_Price_Index'], dtype='str')

In [55]:
population.columns = population.columns.str.strip()
#This removes leading and trailing spaces from all column names

In [56]:
master = pd.merge(
    population,
    housing_yearly,
    on=['City', 'City_ID', 'Year'],
    how='left'
)

master.head()
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 25 non-null     int64
 1   City                 25 non-null     str
 2   City_ID              25 non-null     str
 3   Population           25 non-null     int64
 4   Housing_Price_Index  0 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 1.1 KB

In [57]:
population['City'].unique()

<StringArray>
[       'Montréal CMA', 'Ottawa-Gatineau CMA',         'Toronto CMA',
         'Calgary CMA',       'Vancouver CMA']
Length: 5, dtype: str

In [58]:
housing_yearly['City'].unique()

<StringArray>
[       'Calgary CMA ',        'Montréal CMA', 'Ottawa-Gatineau CMA',
         'Toronto CMA',       'Vancouver CMA']
Length: 5, dtype: str

In [59]:
population['City_ID'].unique()

<StringArray>
[  '2021S0503462', '2021S050535505',   '2021S0503535',   '2021S0503825',
   '2021S0503933']
Length: 5, dtype: str

In [60]:
housing_yearly['City_ID'].unique()

<StringArray>
[  '2011S0503825',   '2011S0503462', '2011S050335505',   '2011S0503535',
   '2011S0503933']
Length: 5, dtype: str

In [61]:
population.dtypes

Year          int64
City            str
City_ID         str
Population    int64
dtype: object

In [62]:
housing_yearly.dtypes

City                       str
City_ID                    str
Year                     int32
Housing_Price_Index    float64
dtype: object

In [63]:
master = pd.merge(
    population,
    housing_yearly,
    on=['City', 'Year'],
    how='left'
)

In [64]:
master.info()
master.head()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 25 non-null     int64
 1   City                 25 non-null     str
 2   City_ID_x            25 non-null     str
 3   Population           25 non-null     int64
 4   City_ID_y            20 non-null     str
 5   Housing_Price_Index  20 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.3 KB

,Year,City,City_ID_x,Population,City_ID_y,Housing_Price_Index
0,2021,Montréal CMA,2021S0503462,4330143,2011S0503462,135.525000
1,2022,Montréal CMA,2021S0503462,4372296,2011S0503462,150.425000
2,2023,Montréal CMA,2021S0503462,4465221,2011S0503462,151.641667
3,2024,Montréal CMA,2021S0503462,4572813,2011S0503462,152.025000
4,2025,Montréal CMA,2021S0503462,4597837,2011S0503462,155.325000

In [65]:
master[master['Housing_Price_Index'].isnull()]

    Year         City     City_ID_x  Population City_ID_y  Housing_Price_Index
15  2021  Calgary CMA  2021S0503825     1540242       NaN                  NaN
16  2022  Calgary CMA  2021S0503825     1587723       NaN                  NaN
17  2023  Calgary CMA  2021S0503825     1680332       NaN                  NaN
18  2024  Calgary CMA  2021S0503825     1783661       NaN                  NaN
19  2025  Calgary CMA  2021S0503825     1836012       NaN                  NaN

In [66]:
housing_yearly[housing_yearly['City']=='Calgary CMA']

Empty DataFrame
Columns: [City, City_ID, Year, Housing_Price_Index]
Index: []

In [67]:
housing_yearly['City'].unique()

<StringArray>
[       'Calgary CMA ',        'Montréal CMA', 'Ottawa-Gatineau CMA',
         'Toronto CMA',       'Vancouver CMA']
Length: 5, dtype: str

In [68]:
housing_yearly['City'] = housing_yearly['City'].str.strip()

In [69]:
housing_yearly['City'].unique()

<StringArray>
[        'Calgary CMA',        'Montréal CMA', 'Ottawa-Gatineau CMA',
         'Toronto CMA',       'Vancouver CMA']
Length: 5, dtype: str

In [70]:
master = pd.merge(
    population,
    housing_yearly,
    on=['City', 'Year'],
    how='left'
)

In [71]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 25 non-null     int64
 1   City                 25 non-null     str
 2   City_ID_x            25 non-null     str
 3   Population           25 non-null     int64
 4   City_ID_y            25 non-null     str
 5   Housing_Price_Index  25 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.3 KB

In [72]:
master = master.drop(columns=['City_ID_y'])
master = master.rename(columns={'City_ID_x':'City_ID'})

In [73]:
master.info()
master.head()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 25 non-null     int64
 1   City                 25 non-null     str
 2   City_ID              25 non-null     str
 3   Population           25 non-null     int64
 4   Housing_Price_Index  25 non-null     float64
dtypes: float64(1), int64(2), str(2)
memory usage: 1.1 KB

   Year          City       City_ID  Population  Housing_Price_Index
0  2021  Montréal CMA  2021S0503462     4330143           135.525000
1  2022  Montréal CMA  2021S0503462     4372296           150.425000
2  2023  Montréal CMA  2021S0503462     4465221           151.641667
3  2024  Montréal CMA  2021S0503462     4572813           152.025000
4  2025  Montréal CMA  2021S0503462     4597837           155.325000

In [74]:
master = pd.merge(
    master,
    income_pivot,
    on=['City'],
    how='left'
)

In [75]:
master.info()

master.head()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  25 non-null     int64
 1   City                  25 non-null     str
 2   City_ID_x             25 non-null     str
 3   Population            25 non-null     int64
 4   Housing_Price_Index   25 non-null     float64
 5   City_ID_y             25 non-null     str
 6   AfterTax_Income_2020  25 non-null     int64
 7   Total_Income_2020     25 non-null     int64
dtypes: float64(1), int64(4), str(3)
memory usage: 1.7 KB

,Year,City,City_ID_x,Population,Housing_Price_Index,City_ID_y,AfterTax_Income_2020,Total_Income_2020
0,2021,Montréal CMA,2021S0503462,4330143,135.525000,2021S0503462,65500,76000
1,2022,Montréal CMA,2021S0503462,4372296,150.425000,2021S0503462,65500,76000
2,2023,Montréal CMA,2021S0503462,4465221,151.641667,2021S0503462,65500,76000
3,2024,Montréal CMA,2021S0503462,4572813,152.025000,2021S0503462,65500,76000
4,2025,Montréal CMA,2021S0503462,4597837,155.325000,2021S0503462,65500,76000

In [76]:
master = master.drop(columns=['City_ID_y'])
master = master.rename(columns={'City_ID_x':'City_ID'})

In [77]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  25 non-null     int64
 1   City                  25 non-null     str
 2   City_ID               25 non-null     str
 3   Population            25 non-null     int64
 4   Housing_Price_Index   25 non-null     float64
 5   AfterTax_Income_2020  25 non-null     int64
 6   Total_Income_2020     25 non-null     int64
dtypes: float64(1), int64(4), str(2)
memory usage: 1.5 KB

In [78]:
master = pd.merge(
    master,
    rental,
    on='City',
    how='left'
)

In [79]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  25 non-null     int64
 1   City                  25 non-null     str
 2   City_ID               25 non-null     str
 3   Population            25 non-null     int64
 4   Housing_Price_Index   25 non-null     float64
 5   AfterTax_Income_2020  25 non-null     int64
 6   Total_Income_2020     25 non-null     int64
 7   Vacancy_2024          25 non-null     float64
 8   Vacancy_2025          25 non-null     float64
 9   Turnover_2024         25 non-null     float64
 10  Turnover_2025         25 non-null     float64
 11  Rent_2024             25 non-null     float64
 12  Rent_2025             25 non-null     float64
 13  RentGrowth_2024       25 non-null     float64
 14  RentGrowth_2025       20 non-null     float64
dtypes: float64(9), int64(4), str(2)
memory usage: 3.1 KB

In [80]:
master.isnull().sum()

Year                    0
City                    0
City_ID                 0
Population              0
Housing_Price_Index     0
AfterTax_Income_2020    0
Total_Income_2020       0
Vacancy_2024            0
Vacancy_2025            0
Turnover_2024           0
Turnover_2025           0
Rent_2024               0
Rent_2025               0
RentGrowth_2024         0
RentGrowth_2025         5
dtype: int64

In [81]:
master.duplicated().sum()

np.int64(0)

In [82]:
#feature engineering
master = master.sort_values(['City', 'Year'])

master['Population_Growth'] = (
    master.groupby('City')['Population']
    .pct_change() * 100
)

In [83]:
master['HPI_Growth'] = (

master.groupby('City')
['Housing_Price_Index']

.pct_change()

*100

)

In [84]:
master.head(10)

,Year,City,City_ID,Population,Housing_Price_Index,AfterTax_Income_2020,Total_Income_2020,Vacancy_2024,Vacancy_2025,Turnover_2024,Turnover_2025,Rent_2024,Rent_2025,RentGrowth_2024,RentGrowth_2025,Population_Growth,HPI_Growth
15,2021,Calgary CMA,2021S0503825,1540242,105.558333,87000,100000,4.8,5.0,23.6,24.9,1882.0,1914.0,8.9,NaN,NaN,NaN
16,2022,Calgary CMA,2021S0503825,1587723,122.791667,87000,100000,4.8,5.0,23.6,24.9,1882.0,1914.0,8.9,NaN,3.082697,16.325886
17,2023,Calgary CMA,2021S0503825,1680332,126.466667,87000,100000,4.8,5.0,23.6,24.9,1882.0,1914.0,8.9,NaN,5.832818,2.992874
18,2024,Calgary CMA,2021S0503825,1783661,131.500000,87000,100000,4.8,5.0,23.6,24.9,1882.0,1914.0,8.9,NaN,6.149320,3.979968
19,2025,Calgary CMA,2021S0503825,1836012,131.383333,87000,100000,4.8,5.0,23.6,24.9,1882.0,1914.0,8.9,NaN,2.935031,-0.088720
0,2021,Montréal CMA,2021S0503462,4330143,135.525000,65500,76000,2.1,2.9,11.1,9.4,1176.0,1346.0,6.3,7.2,NaN,NaN
1,2022,Montréal CMA,2021S0503462,4372296,150.425000,65500,76000,2.1,2.9,11.1,9.4,1176.0,1346.0,6.3,7.2,0.973478,10.994281
2,2023,Montréal CMA,2021S0503462,4465221,151.641667,65500,76000,2.1,2.9,11.1,9.4,1176.0,1346.0,6.3,7.2,2.125314,0.808819
3,2024,Montréal CMA,2021S0503462,4572813,152.025000,65500,76000,2.1,2.9,11.1,9.4,1176.0,1346.0,6.3,7.2,2.409556,0.252789
4,2025,Montréal CMA,2021S0503462,4597837,155.325000,65500,76000,2.1,2.9,11.1,9.4,1176.0,1346.0,6.3,7.2,0.547234,2.170696

In [85]:
master.columns

Index(['Year', 'City', 'City_ID', 'Population', 'Housing_Price_Index',
       'AfterTax_Income_2020', 'Total_Income_2020', 'Vacancy_2024',
       'Vacancy_2025', 'Turnover_2024', 'Turnover_2025', 'Rent_2024',
       'Rent_2025', 'RentGrowth_2024', 'RentGrowth_2025', 'Population_Growth',
       'HPI_Growth'],
      dtype='str')

In [86]:
master[['City',
        'Year',
        'Population',
        'Population_Growth',
        'Housing_Price_Index',
        'HPI_Growth']].head(10)

,City,Year,Population,Population_Growth,Housing_Price_Index,HPI_Growth
15,Calgary CMA,2021,1540242,NaN,105.558333,NaN
16,Calgary CMA,2022,1587723,3.082697,122.791667,16.325886
17,Calgary CMA,2023,1680332,5.832818,126.466667,2.992874
18,Calgary CMA,2024,1783661,6.149320,131.500000,3.979968
19,Calgary CMA,2025,1836012,2.935031,131.383333,-0.088720
0,Montréal CMA,2021,4330143,NaN,135.525000,NaN
1,Montréal CMA,2022,4372296,0.973478,150.425000,10.994281
2,Montréal CMA,2023,4465221,2.125314,151.641667,0.808819
3,Montréal CMA,2024,4572813,2.409556,152.025000,0.252789
4,Montréal CMA,2025,4597837,0.547234,155.325000,2.170696

In [87]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\rezau\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\rezau\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\rezau\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\rezau\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\rezau\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\rezau\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [88]:
from sklearn.preprocessing import MinMaxScaler

In [89]:
scaler = MinMaxScaler()

In [90]:
#creates the scaled variables
master[['Rent_scaled',
        'HPI_scaled',
        'Pop_scaled',
        'Vacancy_scaled']] = scaler.fit_transform(

master[['Rent_2025',
        'Housing_Price_Index',
        'Population_Growth',
        'Vacancy_2025']]
)

In [91]:
#equal weights
master['Housing_Pressure_Score'] = (

    0.25 * master['Rent_scaled']

    + 0.25 * master['HPI_scaled']

    + 0.25 * master['Pop_scaled']

    - 0.25 * master['Vacancy_scaled']

)

In [92]:
master[['City',
        'Year',
        'Housing_Pressure_Score']].head(10)

            City  Year  Housing_Pressure_Score
15   Calgary CMA  2021                     NaN
16   Calgary CMA  2022                0.079102
17   Calgary CMA  2023                0.204274
18   Calgary CMA  2024                0.235766
19   Calgary CMA  2025                0.104953
0   Montréal CMA  2021                     NaN
1   Montréal CMA  2022                0.206328
2   Montréal CMA  2023                0.257559
3   Montréal CMA  2024                0.270510
4   Montréal CMA  2025                0.207198

In [93]:
master[master['Year']==2025][[
    'City',
    'Housing_Pressure_Score'
]].sort_values(
    by='Housing_Pressure_Score',
    ascending=False
)

                   City  Housing_Pressure_Score
9   Ottawa-Gatineau CMA                0.449453
24        Vancouver CMA                0.242156
4          Montréal CMA                0.207198
14          Toronto CMA                0.180491
19          Calgary CMA                0.104953

In [94]:
master[master['Year']==2025][[
'City',
'Rent_2025',
'Housing_Price_Index',
'Population_Growth',
'Vacancy_2025',
'Housing_Pressure_Score'
]].sort_values(
'Housing_Pressure_Score',
ascending=False
)

,City,Rent_2025,Housing_Price_Index,Population_Growth,Vacancy_2025,Housing_Pressure_Score
9,Ottawa-Gatineau CMA,1926.0,162.166667,2.673023,3.0,0.449453
24,Vancouver CMA,2363.0,126.741667,0.205178,3.7,0.242156
4,Montréal CMA,1346.0,155.325000,0.547234,2.9,0.207198
14,Toronto CMA,2046.0,111.041667,-0.013952,3.0,0.180491
19,Calgary CMA,1914.0,131.383333,2.935031,5.0,0.104953

In [95]:
master.shape

(25, 22)

In [96]:
#export to csv
master.to_csv(
    '../../data/clean/final/master.csv',
    index=False
)

In [97]:
import os

os.path.exists('../../data/clean/final/master.csv')

True

In [98]:
os.listdir('../../data/clean/final')

['master.csv']

In [99]:
from sqlalchemy import create_engine

In [100]:
from sqlalchemy import create_engine

engine = create_engine(
    'postgresql://postgres:Postgrerima@localhost:5432/housing_affordability'
)

In [101]:
master.to_sql(
    'master',
    engine,
    if_exists='replace',
    index=False
)

print("Uploaded Successfully!")

Uploaded Successfully!